"""
Data model for the 'notifications' app.
"""

from django.db import models
from django.conf import settings

class Notification(models.Model):
    """
    Represents a single notification message sent to a user.
    
    Notifications can be generated by system events (e.g., fee reminders)
    or sent manually by an admin.
    """
    LEVEL_CHOICES = [
        ("info", "Info"),
        ("warning", "Warning"),
        ("success", "Success"),
        ("error", "Error"),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name="notifications"
    )
    title = models.CharField(max_length=120)
    message = models.TextField(blank=True)
    level = models.CharField(max_length=20, choices=LEVEL_CHOICES, default="info")
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"] # Show newest first

    def __str__(self):
        return f"Notification for {self.user.username}: {self.title}"