# Generated by Django 5.2.8 on 2025-11-08 15:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_admission_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-admission_date', 'reg_no'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9+() -]+$', 'Invalid phone number format.')]),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status'], name='students_en_status_1aff07_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['course_interest'], name='students_en_course__617fde_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['reg_no'], name='students_st_reg_no_de76a0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['active'], name='students_st_active_2899e5_idx'),
        ),
    ]
