# Generated by Django 5.2.8 on 2025-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesreceipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='finance/receipts/'),
        ),
        migrations.AddField(
            model_name='historicalfeesreceipt',
            name='pdf_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
