# Generated by Django 5.2.8 on 2025-11-08 15:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_batch_options_alter_course_options_and_more'),
        ('finance', '0001_initial'),
        ('students', '0004_alter_enquiry_options_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Fee Reminder',
                'verbose_name_plural': 'Fee Reminders',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='feesreceipt',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Fees Receipt', 'verbose_name_plural': 'Fees Receipts'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month', '-id'], 'verbose_name': 'Payroll', 'verbose_name_plural': 'Payroll'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='feesreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='feesreceipt',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.batch'),
        ),
        migrations.AlterField(
            model_name='feesreceipt',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(help_text='Format: "YYYY-MM"', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-(0[1-9]|1[0-2])$', 'Month must be in YYYY-MM format.')]),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('trainer', 'month')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='finance_exp_date_677539_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='finance_exp_categor_54fa26_idx'),
        ),
        migrations.AddIndex(
            model_name='feesreceipt',
            index=models.Index(fields=['receipt_no'], name='finance_fee_receipt_d0a6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='feesreceipt',
            index=models.Index(fields=['date'], name='finance_fee_date_629e10_idx'),
        ),
        migrations.AddIndex(
            model_name='feesreceipt',
            index=models.Index(fields=['mode'], name='finance_fee_mode_8521a0_idx'),
        ),
        migrations.AddIndex(
            model_name='feesreceipt',
            index=models.Index(fields=['locked'], name='finance_fee_locked_a63af2_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['month'], name='finance_pay_month_5d639d_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='finance_pay_status_95b96c_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['trainer'], name='finance_pay_trainer_4a4067_idx'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.batch'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
