# Generated by Django 5.2.8 on 2025-11-06 01:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=30, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('qr_hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('revoked', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
            ],
        ),
    ]
