# Generated by Django 5.2.8 on 2025-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_attendance_days',
            field=models.PositiveIntegerField(default=36, help_text="Total 'Present' days required to complete"),
        ),
    ]
