# Generated by Django 5.2.8 on 2025-11-08 15:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
        ('students', '0004_alter_enquiry_options_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-start_date'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_on'], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['user__first_name'], 'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='capacity',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_weeks',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['code'], name='courses_bat_code_566ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['start_date'], name='courses_bat_start_d_9b4e71_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_cou_code_612388_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['active'], name='courses_cou_active_1b25b8_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='courses_enr_status_4fd017_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['emp_no'], name='courses_tra_emp_no_e082f3_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['is_active'], name='courses_tra_is_acti_1148ab_idx'),
        ),
    ]
