# Generated by Django 5.2.8 on 2025-11-13 15:55

from django.db import migrations

def set_required_days(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')

    # 3 Month Course (12 weeks * 3 days/week = 36)
    Course.objects.filter(duration_weeks=12).update(required_attendance_days=36)

    # 6 Month Course (24 weeks * 3 days/week = 72)
    Course.objects.filter(duration_weeks=24).update(required_attendance_days=72)

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_required_attendance_days'),
    ]

    operations = [
        migrations.RunPython(set_required_days),
    ]