# Generated by Django 5.2.8 on 2025-11-09 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_batch_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Batch Feedback',
                'verbose_name_plural': 'Batch Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
