# Generated by Django 5.2.8 on 2025-11-12 01:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.batch')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], default='P', max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance Entry',
                'verbose_name_plural': 'Attendance Entries',
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance__date_61f2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['batch'], name='attendance__batch_i_d0ecd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('batch', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['status'], name='attendance__status_90a767_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['student'], name='attendance__student_1c90d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceentry',
            unique_together={('attendance', 'student')},
        ),
    ]
